Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20