language: ruby
rvm:
  - 2.2.1
env:
  - RAILS_ENV=test
  - RAILS_VERSION='~> 4.2.4'
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database unidev_test;' -U postgres