language: ruby
rvm:
  - 2.2.1
env:
  - RAILS_ENV=test
branches:
    only:
      - master
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c "CREATE USER unidev WITH PASSWORD 'unidev';" -U postgres
  - psql -c 'create database unidev_test;' -U unidev