development:
  adapter: postgresql
  encoding: unicode
  database: unidev_development
  pool: 5
  username: unidev
  password: unidev

test:
  adapter: postgresql
  encoding: unicode
  database: unidev_test
  pool: 5
  username: unidev
  password: unidev
